## QUESTÃO1

Qual dos códigos abaixo corretamente utiliza broadcasting para construir uma matriz cujas colunas são todas formadas pelos elementos [0,1,2,3]?

In [3]:
import numpy as np
A = np.zeros((4,4))
v = np.arange(4)

In [7]:
A[:] = v
A.T

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [10]:
A[:] = v.reshape(4,1)
A

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [11]:
A[:] = v[:,np.newaxis]
A

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

## Questão2

Qual das alternativas corretamente explica como o array W está sendo calculando no código abaixo?

```python
u = np.random.randint(0,30,7)   
v = np.random.randint(0,30,10).reshape(10,1)
 
W = v + u 
```

In [18]:
u=np.random.randint(0,30,7)
v = np.random.randint(0,30,10).reshape(10,1)
print('v:\n',v)
print('u:\n',u)
print('W:\n',v+u)

v:
 [[10]
 [24]
 [20]
 [ 4]
 [ 1]
 [ 8]
 [ 4]
 [27]
 [11]
 [ 0]]
u:
 [22 14 21  2 22  8  9]
W:
 [[32 24 31 12 32 18 19]
 [46 38 45 26 46 32 33]
 [42 34 41 22 42 28 29]
 [26 18 25  6 26 12 13]
 [23 15 22  3 23  9 10]
 [30 22 29 10 30 16 17]
 [26 18 25  6 26 12 13]
 [49 41 48 29 49 35 36]
 [33 25 32 13 33 19 20]
 [22 14 21  2 22  8  9]]


## Questão3

Considere a matriz abaixo. Utilizando redução, encontre o índice da linha que possui a maior soma dos elementos.
```python
A = np.array([[5, 2, 3, 6, 1, 5, 7, 7, 8, 9], [8, 8, 3, 5, 0, 1, 4, 8, 3, 7], 
              [8, 0, 0, 4, 2, 0, 2, 6, 0, 3], [5, 0, 0, 4, 4, 3, 5, 8, 0, 0], 
              [2, 4, 2, 5, 3, 4, 9, 8, 0, 0], [6, 7, 4, 8, 5, 1, 3, 5, 4, 1], 
              [6, 8, 0, 5, 2, 9, 3, 6, 1, 6], [5, 5, 2, 9, 0, 5, 5, 8, 2, 4], 
              [8, 8, 1, 8, 4, 1, 8, 9, 7, 6], [5, 6, 0, 9, 0, 4, 9, 0, 2, 0]])
```

In [19]:
A = np.array([[5, 2, 3, 6, 1, 5, 7, 7, 8, 9], [8, 8, 3, 5, 0, 1, 4, 8, 3, 7], 
              [8, 0, 0, 4, 2, 0, 2, 6, 0, 3], [5, 0, 0, 4, 4, 3, 5, 8, 0, 0], 
              [2, 4, 2, 5, 3, 4, 9, 8, 0, 0], [6, 7, 4, 8, 5, 1, 3, 5, 4, 1], 
              [6, 8, 0, 5, 2, 9, 3, 6, 1, 6], [5, 5, 2, 9, 0, 5, 5, 8, 2, 4], 
              [8, 8, 1, 8, 4, 1, 8, 9, 7, 6], [5, 6, 0, 9, 0, 4, 9, 0, 2, 0]])

In [37]:
#retorna a posição da linha com a maior soma
np.sum(A,axis=1).argmax()

8

In [35]:
#soma da primeira linha
np.sum([5, 2, 3, 6, 1, 5, 7, 7, 8, 9])

53

In [36]:
A

array([[5, 2, 3, 6, 1, 5, 7, 7, 8, 9],
       [8, 8, 3, 5, 0, 1, 4, 8, 3, 7],
       [8, 0, 0, 4, 2, 0, 2, 6, 0, 3],
       [5, 0, 0, 4, 4, 3, 5, 8, 0, 0],
       [2, 4, 2, 5, 3, 4, 9, 8, 0, 0],
       [6, 7, 4, 8, 5, 1, 3, 5, 4, 1],
       [6, 8, 0, 5, 2, 9, 3, 6, 1, 6],
       [5, 5, 2, 9, 0, 5, 5, 8, 2, 4],
       [8, 8, 1, 8, 4, 1, 8, 9, 7, 6],
       [5, 6, 0, 9, 0, 4, 9, 0, 2, 0]])

## Questão4

Considerando a matriz A do exercício anterior, qual o índice da coluna que possui a menor média de valores?

In [41]:
np.mean(A,axis=0).argmin()

2

## Questão 5

Suponha que a variável A no código abaixo é uma matriz com n linhas e m colunas. O que o código está realizando?
```python
Aargs = np.argsort(A)
A[np.arange(A.shape[0]),Aargs[:,-1]] = -1
```

In [44]:
A=np.random.randint(0,9,15).reshape(3,5)
A

array([[6, 7, 0, 2, 5],
       [1, 2, 8, 6, 5],
       [2, 4, 0, 2, 5]])

In [ ]:
Aargs = np.argsort(A)
A[np.arange(A.shape[0]),Aargs[:,-1]] = -1

In [45]:
Aargs = np.argsort(A)#ordena a posição dos elementos de acordo com o valor do menor para maior
Aargs

array([[2, 3, 4, 0, 1],
       [0, 1, 4, 3, 2],
       [2, 0, 3, 1, 4]], dtype=int64)

In [50]:
A.shape[0]#fornece numero de linha

3

In [46]:
np.arange(A.shape[0])#retorna um array que vai percorrer todo numero ate chegar ao limite maximo da qtd de linhas

array([0, 1, 2])

In [51]:
Aargs[:,-1]#retorna ultima coluna

array([1, 2, 4], dtype=int64)

In [53]:
A[np.arange(A.shape[0]),Aargs[:,-1]]=-1

In [54]:
A

array([[ 6, -1,  0,  2,  5],
       [ 1,  2, -1,  6,  5],
       [ 2,  4,  0,  2, -1]])